apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 827274518702.dkr.ecr.us-west-2.amazonaws.com/flask-api-ecr:latest
          ports:
            - containerPort: 80
