name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest app_test.py

      - name: Build and push Docker image
        env:
          AWS_REGION: us-west-2
          ECR_REGISTRY: flask-api-ecr
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} | aws configure --profile aws-ecr ci
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ~/.aws/credentials
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
          docker build -t ${{ env.ECR_REGISTRY }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.ECR_REGISTRY }}:${{ env.IMAGE_TAG }}
